const cardData = [
  { id: 24, value: 'بافتنی', subject: 'subTwo', imgSrc: './src/assets/images/learn/sub2-12.png' },
  { id: 18, value: 'خیاطی', subject: 'subTwo', imgSrc: './src/assets/images/learn/sub2-6.png' },
  { id: 5, value: 'پیکنیک', subject: 'subOne', imgSrc: './src/assets/images/excite/sub1-5.png' },
  { id: 35, value: 'اسب سواری', subject: 'subThree', imgSrc: './src/assets/images/peace/sub3-11.png' },
  { id: 11, value: 'کاراوکه', subject: 'subOne', imgSrc: './src/assets/images/excite/sub1-11.png' },
  { id: 29, value: 'ماساژ', subject: 'subThree', imgSrc: './src/assets/images/peace/sub3-5.png' },
  { id: 8, value: 'پازل', subject: 'subOne', imgSrc: './src/assets/images/excite/sub1-8.png' },
  { id: 28, value: 'بولینگ', subject: 'subThree', imgSrc: './src/assets/images/peace/sub3-4.png' },
  { id: 32, value: 'دوچرخه سواری', subject: 'subThree', imgSrc: './src/assets/images/peace/sub3-8.png' },
  { id: 10, value: 'حیوان خانگی', subject: 'subOne', imgSrc: './src/assets/images/excite/sub1-10.png' },
  { id: 2, value: 'خانواده', subject: 'subOne', imgSrc: './src/assets/images/excite/sub1-2.png' },
  { id: 9, value: 'موزه', subject: 'subOne', imgSrc: './src/assets/images/excite/sub1-9.png' },
  { id: 20, value: 'بازیافت', subject: 'subTwo', imgSrc: './src/assets/images/learn/sub2-8.png' },
  { id: 27, value: 'ایروبیک', subject: 'subThree', imgSrc: './src/assets/images/peace/sub3-3.png' },
  { id: 25, value: 'صخره نوردی', subject: 'subThree', imgSrc: './src/assets/images/peace/sub3-1.png' },
  { id: 17, value: 'آشپزی', subject: 'subTwo', imgSrc: './src/assets/images/learn/sub2-5.png' },
  { id: 13, value: 'یادگیری زبان', subject: 'subTwo', imgSrc: './src/assets/images/learn/sub2-1.png' },
  { id: 21, value: 'کتاب خواندن', subject: 'subTwo', imgSrc: './src/assets/images/learn/sub2-9.png' },
  { id: 1, value: 'بازی ویدئویی', subject: 'subOne', imgSrc: './src/assets/images/excite/sub1-1.png' },
  { id: 33, value: 'پیاده روی', subject: 'subThree', imgSrc: './src/assets/images/peace/sub3-9.png' },
  { id: 19, value: 'عکاسی', subject: 'subTwo', imgSrc: './src/assets/images/learn/sub2-7.png' },
  { id: 34, value: 'رقص', subject: 'subThree', imgSrc: './src/assets/images/peace/sub3-10.png' },
  { id: 7, value: 'فیلم', subject: 'subOne', imgSrc: './src/assets/images/excite/sub1-7.png' },
  { id: 12, value: 'میراث معماری', subject: 'subOne', imgSrc: './src/assets/images/excite/sub1-12.png' },
  { id: 15, value: 'خوش نویسی', subject: 'subTwo', imgSrc: './src/assets/images/learn/sub2-3.png' },
  { id: 16, value: 'نقاشی', subject: 'subTwo', imgSrc: './src/assets/images/learn/sub2-4.png' },
  { id: 36, value: 'ژیمناستیک', subject: 'subThree', imgSrc: './src/assets/images/peace/sub3-12.png' },
  { id: 6, value: 'پیاده روی', subject: 'subOne', imgSrc: './src/assets/images/excite/sub1-6.png' },
  { id: 14, value: 'نجاری', subject: 'subTwo', imgSrc: './src/assets/images/learn/sub2-2.png' },
  { id: 3, value: 'ماهیگیری', subject: 'subOne', imgSrc: './src/assets/images/excite/sub1-3.png' },
  { id: 30, value: 'یوگا', subject: 'subThree', imgSrc: './src/assets/images/peace/sub3-6.png' },
  { id: 22, value: 'تئاتر', subject: 'subTwo', imgSrc: './src/assets/images/learn/sub2-10.png' },
  { id: 23, value: 'کاردستی', subject: 'subTwo', imgSrc: './src/assets/images/learn/sub2-11.png' },
  { id: 31, value: 'شنا', subject: 'subThree', imgSrc: './src/assets/images/peace/sub3-7.png' },
  { id: 4, value: 'استادیوم', subject: 'subOne', imgSrc: './src/assets/images/excite/sub1-4.png' },
  { id: 26, value: 'بدنسازی', subject: 'subThree', imgSrc: './src/assets/images/peace/sub3-2.png' }
];

export default cardData;
